export const USER_ADDRESSES_REQUEST = "USER_ADDRESSES_REQUEST";
export const USER_ADDRESSES_SUCCESS = "USER_ADDRESSES_SUCCESS";
export const USER_ADDRESSES_FAIL = "USER_ADDRESSES_FAIL";

export const USER_ADDRESS_REQUEST = "USER_ADDRESS_REQUEST";
export const USER_ADDRESS_SUCCESS = "USER_ADDRESS_SUCCESS";
export const USER_ADDRESS_FAIL = "USER_ADDRESS_FAIL";

export const USER_UPDATE_ADDRESS_REQUEST = "USER_UPDATE_ADDRESS_REQUEST";
export const USER_UPDATE_ADDRESS_SUCCESS = "USER_UPDATE_ADDRESS_SUCCESS";
export const USER_UPDATE_ADDRESS_FAIL = "USER_UPDATE_ADDRESS_FAIL";

export const USER_ADD_ADDRESS_REQUEST = "USER_ADD_ADDRESS_REQUEST";
export const USER_ADD_ADDRESS_SUCCESS = "USER_ADD_ADDRESS_SUCCESS";
export const USER_ADD_ADDRESS_FAIL = "USER_ADD_ADDRESS_FAIL";