export const BOOK_LIST_REQUEST = "BOOK_LIST_REQUEST";
export const BOOK_LIST_SUCCESS = "BOOK_LIST_SUCCESS";
export const BOOK_LIST_FAIL = "BOOK_LIST_FAIL";

export const BOOK_DETAILS_REQUEST = "BOOK_DETAILS_REQUEST";
export const BOOK_DETAILS_SUCCESS = "BOOK_DETAILS_SUCCESS";
export const BOOK_DETAILS_FAIL = "BOOK_DETAILS_FAIL";

export const BOOK_DETAILS_ONE_REQUEST = "BOOK_DETAILS_ONE_REQUEST";
export const BOOK_DETAILS_ONE_SUCCESS = "BOOK_DETAILS_ONE_SUCCESS";
export const BOOK_DETAILS_ONE_FAIL = "BOOK_DETAILS_ONE_FAIL";

export const BOOK_DELETE_REQUEST = "BOOK_DELETE_REQUEST";
export const BOOK_DELETE_SUCCESS = "BOOK_DELETE_SUCCESS";
export const BOOK_DELETE_FAIL = "BOOK_DELETE_FAIL";

export const EDITION_DELETE_REQUEST = "EDITION_DELETE_REQUEST";
export const EDITION_DELETE_SUCCESS = "EDITION_DELETE_SUCCESS";
export const EDITION_DELETE_FAIL = "EDITION_DELETE_FAIL";

export const BOOK_ADD_REQUEST = "BOOK_ADD_REQUEST";
export const BOOK_ADD_SUCCESS = "BOOK_ADD_SUCCESS";
export const BOOK_ADD_FAIL = "BOOK_ADD_FAIL";
export const BOOK_ADD_RESET = "BOOK_ADD_RESET";

export const EDITION_ADD_REQUEST = "EDITION_ADD_REQUEST";
export const EDITION_ADD_SUCCESS = "EDITION_ADD_SUCCESS";
export const EDITION_ADD_FAIL = "EDITION_ADD_FAIL";
