export const CART_ADD_BOOK_REQUEST = "CART_ADD_BOOK_REQUEST";
export const CART_ADD_BOOK_SUCCESS = "CART_ADD_BOOK_SUCCESS";
export const CART_ADD_BOOK_FAIL = "CART_ADD_BOOK_FAIL";

export const CART_REMOVE_BOOK_REQUEST = "CART_REMOVE_BOOK_REQUEST";
export const CART_REMOVE_BOOK_SUCCESS = "CART_REMOVE_BOOK_SUCCESS";
export const CART_REMOVE_BOOK_FAIL = "CART_REMOVE_BOOK_FAIL";

export const CART_UPDATE_BOOK_REQUEST = "CART_UPDATE_BOOK_REQUEST";
export const CART_UPDATE_BOOK_SUCCESS = "CART_UPDATE_BOOK_SUCCESS";
export const CART_UPDATE_BOOK_FAIL = "CART_UPDATE_BOOK_FAIL";

export const CART_GET_BOOK_REQUEST = "CART_GET_BOOK_REQUEST";
export const CART_GET_BOOK_SUCCESS = "CART_GET_BOOK_SUCCESS";
export const CART_GET_BOOK_FAIL = "CART_GET_BOOK_FAIL";
