export const REQUEST_MY_ORDERS = "REQUEST_MY_ORDERS";
export const SUCCESS_MY_ORDERS = "SUCCESS_MY_ORDERS";
export const FAIL_MY_ORDERS = "FAIL_MY_ORDERS";

export const REQUEST_ALL_ORDERS = "REQUEST_ALL_ORDERS";
export const SUCCESS_ALL_ORDERS = "SUCCESS_ALL_ORDERS";
export const FAIL_ALL_ORDERS = "FAIL_ALL_ORDERS";

export const REQUEST_ONE_ORDER = "REQUEST_ONE_ORDER";
export const SUCCESS_ONE_ORDER = "SUCCESS_ONE_ORDER";
export const FAIL_ONE_ORDER = "FAIL_ONE_ORDER";
export const RESET_ONE_ORDER = "RESET_ONE_ORDER";

export const REQUEST_ADD_ORDERS = "REQUEST_ADD_ORDERS";
export const SUCCESS_ADD_ORDERS = "SUCCESS_ADD_ORDERS";
export const FAIL_ADD_ORDERS = "FAIL_ADD_ORDERS";

export const REQUEST_ORDER_DELIVER = "REQUEST_ORDER_DELIVER";
export const SUCCESS_ORDER_DELIVER = "SUCCESS_ORDER_DELIVER";
export const FAIL_ORDER_DELIVER = "FAIL_ORDER_DELIVER";

export const REQUEST_ORDER_PAY = "REQUEST_ORDER_PAY";
export const SUCCESS_ORDER_PAY = "SUCCESS_ORDER_PAY";
export const FAIL_ORDER_PAY = "FAIL_ORDER_PAY";
