export const REQUEST_MY_ORDERS = "REQUEST_MY_ORDERS";
export const SUCCESS_MY_ORDERS = "SUCCESS_MY_ORDERS";
export const FAIL_MY_ORDERS = "FAIL_MY_ORDERS";

export const REQUEST_ALL_ORDERS = "REQUEST_ALL_ORDERS";
export const SUCCESS_ALL_ORDERS = "SUCCESS_ALL_ORDERS";
export const FAIL_ALL_ORDERS = "FAIL_ALL_ORDERS";

export const REQUEST_ONE_ORDERS = "REQUEST_ONE_ORDERS";
export const SUCCESS_ONE_ORDERS = "SUCCESS_ONE_ORDERS";
export const FAIL_ONE_ORDERS = "FAIL_ONE_ORDERS";

export const REQUEST_ADD_ORDERS = "REQUEST_ADD_ORDERS";
export const SUCCESS_ADD_ORDERS = "SUCCESS_ADD_ORDERS";
export const FAIL_ADD_ORDERS = "FAIL_ADD_ORDERS";
